# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19TTzencbzsANSIhy9u0S9BW_ujUrOgdH
"""

a=[]
n=1
for p in range(5):
  a.append(n)
  n+=1
  print("%3d" %a[p],end="")

sum=0
for i in range(101):
  sum=sum+i
print(sum)

sum=0
for i in range(101):
  if(i%5==0):
    sum=sum+i
print(sum)

cnt=0
for i in range(101):
  if(i%5==0 and i!=0):
    cnt+=1
print(cnt)

a=int(input("하나의 정수를 입력하라"))
for i in range(1,10):
  print(a,"*",i,"=",a*i)

a,b=input("두 개의 정수를 입력하라").split()
a=int(a)
b=int(b)
for i in range(1,10):
  for j in range(a,b+1):
    print(j,"*",i,"=",j*i," ",end="")
  print()

sum=0
for i in range(1,101):
  if(i%2==0):
    i=i*-1
    sum=sum+i
  else:
    sum=sum+i
print(sum)

a=[1,2,3,4,5,6,7,8,9,10]
for i in range(0,10):
  print(a[i:10])

x=int(input("x?"))
y=int(input("y?"))
print(x**y)

n=int(input("N?"))
sum=0
for i in range(1,n+1):
  sum+=i
print(sum)

n=int(input("N?"))
for i in range(1,n+1):
  for j in range(1,i+1):
    print("*",end="")
  print()

n=int(input("N?"))
for i in range(1,n+1):
  for k in range(i+1,n+1):
    print(" ",end="")
  for j in range(1,i+1):
    print("*",end="")
  print()

a=int(input("N="))
n=1
t=1
for i in range(0,a//2+1):
  for j in range(i,a//2+1):
    print("\t",end="")
  for k in range(0,t):
    print("\t",n,end="")
    n+=1
  t+=2
  print()
t=3

for i in range(0,a//2):
  for j in range(0,i+2):
    print("\t",end="")
  for k in range(0,t):
    print("\t",n,end="")
    n+=1
  t-=2
  print()

n=int(input("N="))
for i in range(0,n):
  for j in range(0,i+1):
    print("*",end="") #별찍기 

  for k in range(i,n+1):
    print(" ",end="") #첫띄어쓰기

  print(" ",end="") #중간 띄어쓰기

  for n in range(i,n+1):
    print(" ",end="") #마지막 띄어쓰기

  for t in range(0,i+1):
    print("*",end="")

  print()

n=int(input("N="))
for i in range(0,n+1):
  for j in range(0,i):
    print("*",end="")

  print(" ",end="")

  for k in range(i,n):
    print("*",end="")
  print()



