# -*- coding: utf-8 -*-
"""02.09

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/198_oBYXncQ9N4O1O7T9aynCGLdKnSEYE
"""

n=int(input("숫자를 입력하세요:"))
a=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
for j in range(1,n+1):
    print(a[0:j])

w='y'
while(w=='y'):
  n=input("문자열을 입력하세요: ")
  m=int(input("숫자를 입력하세요:"))
  for i in range(m):
   print(n)
  w=input("다시 실행하시겠습니까?")

a,b=input("문자열을 두개 입력하세용").split()
print(a,b,sep="")

a,b=input("문자열 두 개를 입력하세요:").split()
c=a+b
length=len(c)
print("총 문자열의 길이는 ",length,"이다",sep="")
aph=input("찾고자 하는 문자는?")
print("문자열 중에서",c.find(aph)+1,"번째 위치에서 처음으로 '",aph,"'문자가 발견되었다.",end="")

a=input("문자열을 입력하세요")
aph=input("찾고자 하는 문자는?")
print("'",aph,"'의 개수는 ",a.count(aph),"개 입니다",sep="")

a=input("문자열을 입력하시오:")
length=len(a)
max=0
aph=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
cnt=[]
for i in range(26):
  k=a.count(aph[i])
  cnt.append(k)

for i in range(26):
  if(cnt[i]>=max):
    max=cnt[i]
    imsi=i

print("가장 많이 사용된 알파벳은 ",aph[imsi],"이며 ",max,"개입니다.",sep="")

a=input("문자열을 입력하세요 :")
length=len(a)
number=0
aph=0
symbol=0
for i in range(length):
  if(a[i]>='a' and a[i]<'z'):
    aph+=1
  elif(a[i]>='0' and a[i]<='9'):
    number+=1
  else:
    symbol+=1
print(number,aph,symbol,end="")

n=input("문자열을 입력하세요:")
print("알파벳의 개수는 다음과 같습니다.")
aph=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
cnt=[]
for i in range(26):
  k=n.count(aph[i])
  cnt.append(k)
for i in range(26):
  print(aph[i],"=",cnt[i],sep="")

n=input("문자열을 입력하세요:")
aph="abcdefghijklmn"
aphB="ABCDEFGHIJKLMN"
result=[]

length=len(n)
for i in range(length):
  if(n[i]>='a' and n[i]<='z'):
    k=aph.find(n[i])
    result.append(aphB[k])
  else:
    k=aphB.find(n[i])
    result.append(aph[k])
print("".join(result))

mun=""
ex=""
n=1
while(1):

  if(n==1 or n==2 or n==3 or n==4 or n==5):
    print("현재문자열:",mun)
    print("1)문자열 2)부분복사 3)추가 4)부분추가 5)종료")
    n=int(input("번호를 입력하세요:"))
  else:
    n=int(input("번호를 입력하세요:"))
  if(n==1):
    ex=input("문자열을 입력하세요")
    mun=ex
  elif(n==2):
    number=int(input("숫자를 입력하세요"))
    ex=input("문자열을 입력하세요")
    mun=ex[0:number]
  elif(n==3):
    ex=input("문자열을 입력하세요")
    mun=mun+ex
  elif(n==4):
    ex=input("문자열을 입력하세요")
    mun=mun+ex[0:number]
  elif(n==5):
    print("프로그램을 종료합니다.")
    break
  else:
    print("잘못 입력되었습니다.")
    n=6

n=int(input("N?"))
print(10000000000+n)

ID="KIM"
PW="KKKK"

id=input("ID=")
pw=input("PW=")
if(id==ID and pw==PW):
  print("로그인 되었습니다.")
elif(id==ID and pw!=PW):
  print("비밀번호가 틀렸습니다.")
elif(id!=ID and pw==PW):
  print("아이디가 틀렸습니다.")
else:
  print("회원이 아닙니다.")

m=input("꽃님이에게 보내는 문자열")
wrong=input("문자열 안에서 잘못된 문자는?")
right=input("잘못된 문자 대신 바꿔질 문자는?")
length=len(m)
n=list(m)
for i in range(length):
  if(n[i]==wrong):
    n[i]=right
print("".join(n))