# -*- coding: utf-8 -*-
"""02.08

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13TPDc3PFxCh2P9f1RZOUxlFvty84Je7H
"""

n=int(input("N="))
for i in range(0,n+1):
  for j in range(i,n):
    print("*",end="")
  print(" ",end="")
  for j in range(i,0,-1):
    print("*",end="")
  print()

n=int(input("N="))
num=1
start=num
k=1
j=0
for i in range(0,n):
  for g in range(i,n):
    print(" ",end="")
  for j in range(0,k):
    print(start,end="")
    start+=1
  for p in range(start-2,j,-1):
    print(p,end="")
  j+=1
  num+=1
  start=num
  k+=1
  print()

n=int(input("N="))
for i in range(0,n):
  for j in range(0,i):
    print(" ",end="")
  print("*",end="")
  print()

n,b,c=input().split()
num=[]
n=int(n)
b=int(b)
c=int(c)

if(b>c):
  r=b
  t=c
else:
  r=c
  t=b

cnt=0

for i in range(n):
  k=int(input())
  num.append(k)

for j in range(0,n):
  if(num[j]<=r and num[j]>=t):
    cnt+=1
print(cnt)

print("<입력>")
a,b=input().split()
a=int(a)
b=int(b)
print("<출력>")
if(a%b==0):
  print("'",a,"'는 '",b,"'의 배수이다.")
elif(b%a==0):
  print("'",a,"'는 '",b,"'의 약수이다.")
else:
  print("'",a,"'과 '",b,"'는 아무관계도 없다")

print("<입력>")
a,b=input().split()
a=int(a)
b=int(b)
cnt=0
print("<출력>")
while(1):
  c=a//b
  a=c
  cnt+=1
  if(c==0):
    break
print(cnt)

print("<입력>")
cnt=0
n=int(input())
print("<출력>")
for i in range(1,n+1):
  if(n%i==0):
    cnt+=1
print(cnt)

n=int(input("1일은 무슨 요일입니까(0~6)"))
max=int(input("총 며칠입니까?"))

date=["일","월","화","수","목","금","토"]
for i in range(7):
  print("\t",date[i],end="")
print()
for i in range(n):
  print("\t",end="")
for day in range(1,max+1):
  print("\t",day,end="")
  if((day+n)%7==0):
    print()

one,two=input().split()
one=int(one)
two=int(two)

if(one>two):
  m=one
  n=two
else:
  m=two
  n=one

while(1):
  c=m%n
  if(c==0):
    break
  m=n
  n=c

print(n,"%0.1d"%(one*two/n))

num=[]
sum=0
for i in range(5):
  k=int(input())
  num.append(k)
for i in range(5):
  sum=sum+num[i]
print(sum,"%0.1d"%(sum/5),end="")

num=[]
for i in range(10):
  k=int(input())
  num.append(k)

max=num[0]

for j in range(10):
  if(num[j]>max):
    max=num[j]
print(max)

print("1부터 50까지의 정수 중에 4의 배수의 총합은?")
sum=0
for i in range(1,51):
  if(i%4==0):
    sum+=i
    print(i," ",end="")
    print()

print(sum,"이다",end="")

print("소문자 10개를 입력하시오")
n=input()
length=len(n)
print("출력 :",end="")
for i in range(length-1,-1,-1):
  print(n[i],end="")

print("10개의 숫자를 입력하시오")
num=[]
for i in range(10):
  k=int(input())
  num.append(k
             )
print("찾을 수를 입력하시오")
n=int(input())
for i in range(10):
  if(i==n):
    print(n,"은 당신이 ",i,"번째 입력한 수 입니다.",end="")
    t=1
if(t!=1):
  print(n,"은 당신이 입력한 수에 없습니다.",end="")

n=int(input("N?"))
nam=[]
j=0
while(1):
  c=n%2
  nam.append(c)
  n=n//2
  j+=1
  if(n==0):
    break
for i in range(j-1,-1,-1):
  print(nam[i],end="")

print("10명의 학생 키를 입력하시오")
num=[]
sum=0
for i in range(10):
  k=int(input())
  num.append(k)
max=0
min=999
for i in range(10):
  sum+=num[i]
  if(num[i]>max):
    max=num[i]
  if(num[i]<min):
    min=num[i]
print(max,min,"%0.01f"%(sum/10),end="")

num="ABCDEFGH"
lst=list(num)
print(num)

for j in range(8):
  imsi=lst[0]
  for i in range(7):
    lst[i]=lst[i+1]
  lst[7]=imsi

num="".join(lst)
print(num)