# -*- coding: utf-8 -*-
"""02.10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ixOjWf5N_Evu4dhVtpATso3Z68EjpnDs
"""

arr=[[" "]*5 for i in range(5)]
n=1
t=3
for y in range(0,5):
  for x in range(4,t,-1):
    arr[y][x]=n
    n+=1
  t-=1
for y in range(0,5):
  for x in range(0,5):
    print("\t",arr[y][x],end="")
  print()

arr=[[" "]*5 for i in range(5)]
n=1
t=4
for y in range(0,5):
  for x in range(4,y-1,-1):
    arr[y][x]=n
    n+=1
  
for y in range(0,5):
  for x in range(0,5):
    print("\t",arr[y][x],end="")
  print()

arr=[[" "]*5 for i in range(5)]
n=1
for x in range(0,5):
  for y in range(0,x+1):
    arr[y][x]=n
    n+=1

for y in range(5):
  for x in range(5):
    print("\t",arr[y][x],end="")
  print()

arr=[[" "]*5 for i in range(5)]
n=1
start=5//2
end=5//2
for y in range(3):
  for x in range(start,end+1):
    arr[y][x]=n
    n+=1
  start-=1
  end+=1

start+=2
end-=2

for y in range(3,5):
  for x in range(start,end+1):
    arr[y][x]=n
    n+=1
  start+=1
  end-=1

for y in range(5):
  for x in range(5):
    print("\t",arr[y][x],end="")
  print()

arr=[[" "]*5 for i in range(5)]
n=1
start=5//2
end=5//2
for x in range(3):
  for y in range(start,end+1):
    arr[y][x]=n
    n+=1
  start-=1
  end+=1

start+=2
end-=2

for x in range(3,5):
  for y in range(start,end+1):
    arr[y][x]=n
    n+=1
  start+=1
  end-=1

for y in range(5):
  for x in range(5):
    print("\t",arr[y][x],end="")
  print()

arr=[[" "]*5 for i in range(5)]
n=1
start=5//2
end=5//2
for x in range(4,1,-1):
  for y in range(start,end-1,-1):
    arr[y][x]=n
    n+=1
  start+=1
  end-=1

start-=2
end+=2

for x in range(1,-1,-1):
  for y in range(start,end-1,-1):
    arr[y][x]=n
    n+=1
  start-=1
  end+=1

for y in range(5):
  for x in range(5):
    print("\t",arr[y][x],end="")
  print()

arr=[[" "]*5 for i in range(5)]
n=1
start=5//2
end=5//2
for y in range(4,1,-1):
  for x in range(start,end-1,-1):
    arr[y][x]=n
    n+=1
  start+=1
  end-=1

start-=2
end+=2

for y in range(1,-1,-1):
  for x in range(start,end-1,-1):
    arr[y][x]=n
    n+=1
  start-=1
  end+=1

for y in range(5):
  for x in range(5):
    print("\t",arr[y][x],end="")
  print()

arr=[["x"]*100 for i in range(5)]
for i in range(5):
  arr[i]=input()

for i in range(5):
  length=len(arr[i])
  for j in range(length):
    if(arr[i][j]=='a' or arr[i][j]=='e' or arr[i][j]=='i' or arr[i][j]=='o' or arr[i][j]=='u'):
      print(arr[i][j],end="")
  print()

arr=[[0]*100 for i in range(20)]
i=0
cnt=0
while(1):
  arr[i]=input()
  cnt+=1
  if(arr[i]=='stop'):
    break
  i+=1
print("입력이 완료 되었습니다.")
wrong=input("수정할 문자를 입력하세요")
right=input("채워질 문자를 입력하세요")
print("변경된 문자열은 다음과 같습니다")

for i in range(cnt-1):
  lst[i]=list(arr[i])

for i in range(cnt-1):
  length=len(lst[i])
  for j in range(length):
    if(lst[i][j]==wrong):
      lst[i][j]=right
for i in range(cnt-1):
  print("".join(lst[i]))

def sum(a):
  sum=0
  for i in range(a+1):
    sum=sum+i
  return sum
num=int(input("정수를 입력하시오"))
print("1부터 ",num,"까지의 합은 ",sum(num),"입니다",sep="")

def yak(num):
  cnt=0
  arr=[]
  for i in range(1,num+1):
    if(num%i==0):
      arr.append(i)
      cnt+=1
  print("주어진 정수의 약수는 ",end="")
  for j in range(cnt):
    print(arr[j],end=" ")
  print("입니다.")
  

n=int(input("정수를 입력하시오"))
c=yak(n)

def prime(num):
  k=0
  for i in range(2,num):
    if(num%i==0):
      k=1
  if k==0:
    print(num,"는 소수입니다.")
  else:
    print(num,"는 소수가 아닙니다")
num=int(input("정수를 입력하시오"))
result=prime(num)

n=int(input())
n1=n//10
n2=n%10
if(n2==0):
  result=n1*2
else:
  result=(n2*10+n1)*2

if(result>=100):
  n3=result//100
  result=result-n3*100

print(result)
if(result<=50):
  print("GOOD")
else:
  print("OH MY GOD")

a,b=input().split()
a=int(a)
b=int(b)
if(a>b):
  print(">")
elif(a<b):
  print("<")
else:
  print("=")

a,b=input().split()
a=int(a)
b=int(b)
if(a>b):
  m=a
  n=b
else:
  m=b
  n=a

print(m-n)

n=int(input())
if(n%7==0):
  print("multiple")
else:
  print("not multiple")

n=int(input())

if(n%400==0):
  print("Leap")
elif(n%4==0 and n%100!=0):
  print("Leap")
else:
  print("Normal")

arr=[]
for i in range(3):
  k=int(input())
  arr.append(k)
arr.sort()
print(arr[1])

hour,minute=input().split()
hour=int(hour)
minute=int(minute)
realminute=minute-30
if(realminute<0):
  hour-=1
  realminute=60-(30-minute)
print(hour,realminute,end="")

score=int(input())
if(score>=90):
  print("A")
elif(score<90 and score>=80):
  print("B")
elif(score<80 and score>=70):
  print("C")
elif(score<70 and score>=60):
  print("D")
else:
  print("F")

a,b,c,d=input().split()
cnt=0
a=int(a)
b=int(b)
c=int(c)
d=int(d)

if(a==1):
  cnt+=1
if(b==1):
  cnt+=1
if(c==1):
  cnt+=1
if(d==1):
  cnt+=1

if(cnt==0):
  print("모")
elif(cnt==1):
  print("도")
elif(cnt==2):
  print("개")
elif(cnt==3):
  print("걸")
elif(cnt==4):
  print("윷")

a,b=input().split()
a=int(a)
b=int(b)

arr=[400,340,170,100,70]
one=arr[a-1]
two=arr[b-1]
if(one+two>=500):
  print("angry")
else:
  print("no angry")

a,b,c=input().split()
a=int(a)
b=int(b)
c=int(c)
if(a>b and a>c):
  if(a<b+c):
    print("yes")
  else:
    print("no")

elif(b>a and b>c):
  if(b<a+c):
    print("yes")
  else:
    print("no")

elif(c>a and c>b):
  if(c<a+b):
    print("yes")
  else:
    print("no")

year,month=input().split()
year=int(year)
month=int(month)

if(month==2):
  if(year%400==0 or (year%4==0 and year%100!=0) ):
    print("29")
  else:
    print("28")

elif(month==1 or month==3 or month==5 or month==7 or month==8 or month==10 or month==12):
  print("31")
else:
  print("30")

