# -*- coding: utf-8 -*-
"""02.13

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dixplgNeZeaMH852zc9glOb7a7keLkmO
"""

import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

import pandas as pd
import matplotlib.pyplot as plt
plt.plot([1,2,3,4,5])
plt.xlabel("x number")
plt.ylabel("y number")
plt.show()

import matplotlib.pyplot as plt
x=list(range(-5,11))
y=[]
for j in range(16):
  y.append(x[j]**2+4)
  
plt.plot(x,y)
plt.grid(color='0.8')
plt.show()
print('min:',min(y))

import matplotlib.pyplot as plt
import numpy as np
x=np.arange(-10,11)
y=x**2
plt.plot(x,y,'m*')
plt.grid(color='0.9')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.arange(-10,11)
y=x**2

plt.plot(x,y,'m*')
plt.grid(color='0.9')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.arange(-5,6)
y=x**2
y2=-1*x**2

plt.plot(x,y)
plt.plot(x,y2)
plt.grid()
plt.show()

import matplotlib.pyplot as plt
from numpy.random import rand
a=rand(100)
b=rand(100)
plt.scatter(a,b)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
from numpy.random import rand
a=rand(100)
b=rand(100)
plt.scatter(a,b)
plt.grid(color='0.9')
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
randata=np.random.rand(30)
print(randata)

sedata=pd.Series(randata)
sedata.plot()

plt.show()

num=[]
for i in range(7):
  k=int(input())
  num.append(k)
num.sort()
print(num[6])
print(num[5])

a,b=input().split()
a=int(a)
b=int(b)
print(a,"+",b,"=",a+b,sep="")
print(a,"-",b,"=",a-b,sep="")
print(a,"*",b,"=",a*b,sep="")
print(a,"/",b,"=",a//b,sep="")

a,b=input().split()
a=int(a)
b=int(b)
print("%0.1f"%(a*b/2))

num=[]
hol=[]
sum=0
check=0
for i in range(7):
  k=int(input())
  num.append(k)
for i in range(7):
  if(num[i]%2!=0):
    hol.append(num[i])
    check=1
if check==1:
  length=len(hol)
  hol.sort()
  for i in range(length):
    sum=sum+hol[i]
  print(sum)
  print(hol[0])
elif check==0:
  print('-1')

answer=[]
score=0 ##해당 문제에서 받는 점수
sum=[] ##스코어의 집합
hab=0
q=int(input())
for i in range(q):
  k=int(input())
  answer.append(k)

for i in range(q):
  if(answer[i]==1):
    score=1
    for j in range(1,i):
      if(answer[i-j]==1):
        score+=1
      elif(answer[i-j]==0):
        break;
  elif answer[i]==0:
    score=0
  sum.append(score)

for i in range(q):
  hab=hab+sum[i]
print(hab)

first=[]
second=[]
third=[]
cnt=0
for i in range(4):
  k=int(input())
  first.append(k)

for i in range(4):
  k=int(input())
  second.append(k)

for i in range(4):
  k=int(input())
  third.append(k)

for i in range(4):
  if(first[i]==0):
    cnt+=1
if(cnt==1):
  print("도")
elif(cnt==2):
  print("개")
elif(cnt==3):
  print("걸")
elif(cnt==4):
  print("윷")
else:
  print("모")
cnt=0

for i in range(4):
  if(second[i]==0):
    cnt+=1
if(cnt==1):
  print("도")
elif(cnt==2):
  print("개")
elif(cnt==3):
  print("걸")
elif(cnt==4):
  print("윷")
else:
  print("모")
cnt=0

for i in range(4):
  if(third[i]==0):
    cnt+=1
if(cnt==1):
  print("도")
elif(cnt==2):
  print("개")
elif(cnt==3):
  print("걸")
elif(cnt==4):
  print("윷")
else:
  print("모")

enter=[]
exit=[]
people=[]
max=0

for i in range(4):
  exi,ent=input().split()
  ent=int(ent)
  exi=int(exi)
  enter.append(ent)
  exit.append(exi)
k=0
for i in range(4):
  k=k+enter[i]-exit[i]
  people.append(k)

for i in range(4):
  if(people[i]>max):
    max=people[i]
print(max)

hour,min=input().split()
add=int(input())
hour=int(hour)
min=int(min)
cnt=0

realhour=hour
realmin=min+add

if(realmin>=60):
  while(realmin>=60):
    realmin=realmin-60
    cnt+=1

  realhour=realhour+cnt
  if realhour>=24:
    while(realhour>=24):
      realhour=realhour-24
print(realhour,realmin,end="")

hour,min,second=input().split()
time=0
hour=int(hour)
min=int(min)
second=int(second)
add=int(input())
time=hour*3600+min*60+second+add
realhour=time//3600
realmin=(time%3600)//60
realsecond=(time%3600)%60

if(realhour>=24):
  while(realhour>=24):
    realhour=realhour-24
print(realhour,realmin,realsecond)

country=[]
student=[]
score=[]
imsiscore=[]
num=int(input())

for i in range(num):
  a,b,c=input().split()
  a=int(a)
  b=int(b)
  c=int(c)

  country.append(a)
  student.append(b)
  score.append(c)

for i in range(num):
  imsiscore.append(score[i])

score.sort()

for i in range(num):
  if(score[num-1]==imsiscore[i]):
    gold=i
  if(score[num-2]==imsiscore[i]):
    silver=i
j=0

while(1):
  for i in range(num):
    if(score[num-3-j]==imsiscore[i]):
      cop=i

  if(country[silver]==country[cop]):
    j+=1
  else:
    break

print(country[gold]," ",student[gold],sep="")
print(country[silver]," ",student[silver],sep="")
print(country[cop]," ",student[cop],sep="")

plate=input()
length=len(plate)
sum=10
for i in range(1,length):
  if(plate[i-1]==plate[i]):
    sum+=5
  else:
    sum+=10
print(sum)

ten=['0','1','2','3','4','5','6','7','8','9']
twelve=['A','B','C','D','E','F','G','H','I','J','K','L']
num=int(input())
year=num-2013
m=9
n=5
for i in range(year):
  m+=1
  n+=1
  if(m==10):
    m=0
  if(n==12):
    n=0
print(twelve[n],ten[m],sep="")

