# -*- coding: utf-8 -*-
"""02.16

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PpSEQohXNZKIPNvDelCGyX0XoJKoDRvf
"""

a=input()
arr=list(a)
length=len(a)
for i in range(length):
  if(arr[i]==" "):
    arr[i]='*'
for i in range(6-(length%6)):
  arr.append(".")

lengths=len(arr)

if(length%6==0):
  xero=length//6
else:
  xero=length//6+1

k=0
arrange=[[""]*6 for i in range(xero)]
for i in range(xero):
  for j in range(6):
    arrange[i][j]=arr[k]
    k+=1

for i in range(xero):
  for j in range(6):
    print(arrange[j][i],end="")

haab=['pop', 'no', 'zip', 'zotz', 'tzec', 'xul', 'yoxkin', 'mol', 'chen', 'yax', 'zac', 'ceh', 'mac', 'kankin', 'muan', 'pax', 'koyab', 'cumhu','uayet']
tzolkin=['imix', 'ik', 'akbal', 'kan', 'chicchan', 'cimi', 'manik', 'lamat', 'muluk', 'ok', 'chuen', 'eb', 'ben', 'ix', 'mem', 'cib', 'caban', 'eznab', 'canac', 'ahau']
day,month,year=input().split()
day=int(day)
year=int(year)

days=(year*365)+day ##날 수
years=days//260+1
print(years)

num=days%20
aph=num%20
date=num%13
print(tzolkin[aph])
print(date)

num=int(input())
arr=[]
sum=0
for i in range(num):
  k=int(input())
  arr.append(k) ##처음 숫자 기입
arr.sort()

while(1):
  k=int(input())
  if(k==0):
    break
  arr.append(k)
  arr.sort()
  if k>avg:
    del arr[0]
  elif k<avg:
    del arr[num]
  print(arr)
  for i in range(num):
    sum=sum+arr[i]
  print("%0.1f"%(sum/num))
  sum=0

num=int(input())
k=0
while(k<=num):
  for i in range(1,num+1):
    for j in range(1,i+1):
      k+=1
print(j)

num=int(input())
arr=[]
sum=0
for i in range(num):
  k=int(input())
  arr.append(k)
  sum+=k
result=sum//num
cnt=0
for i in range(num):
  if(arr[i]>result):
    while(1):
      arr[i]-=1
      cnt+=1
      if(arr[i]==result):
        break
  elif(arr[i]>result):
    while(1):
      result-=1
      cnt+=1
      if(arr[i]==result):
        break
  elif(arr[i]==result):
    while(1):
      break
print(cnt)

num=int(input())
arr=[['0']*num for i in range(num)]
k=2
m=1
if(num%2!=0):
  arr[num//2][num//2-1]=1
  i=num//2
  j=num//2-1
  while(1):
    if(m==1):
      while(1):
        if(arr[i+1][j]=='0'):
          m=2
          break
        j+=1
        arr[i][j]=k
        k+=1
    elif(m==2):
     while(1):
       if(arr[i][j-1]=='0'):
         m=3
         break
       i-=1
       arr[i][j]=k
       k+=1
    elif(m==3):
     while(1):
       if(arr[i-1][j]=='0'):
         m=4
         break
       j-=1
       arr[i][j]=k
       k+=1
    elif(m==4):
     while(1):
        if(arr[i][j-1]=='0'):
          m=1
          break
        i-=1
        arr[i][j]=k
        k+=1
    if(k==num*num):
      break

print(arr)





