# -*- coding: utf-8 -*-
"""02.14

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B4zbruLG1SiYr2CIkeYxqqOCk95tcizA
"""

num=int(input())
a=num//300
b=(num%300)//60
if(((num%300)%60)%10==0):
  c=((num%300)%60)//10
  print(a,b,c,end="")
else:
  print('-1')

num=int(input())
student=[]
apple=[]
namerge=0
for i in range(num):
  a,b=input().split()
  a=int(a)
  b=int(b)
  student.append(a)
  apple.append(b)

for i in range(num):
  c=apple[i]%student[i]
  namerge+=c
print(namerge)

num=int(input())
score=[]
for i in range(num):
  n=int(input())
  score.append(n)
score.sort()
print(score[num-1]-score[0])

a,b=input().split()
a=int(a)
b=int(b)
if(a%2==0):
  print("짝수",end="")
else:
  print("홀수",end="")
print("+",end="")
if(b%2==0):
  print("짝수",end="")
else:
  print("홀수",end="")
print("=",end="")
if((a+b)%2==0):
  print("짝수",end="")
else:
  print("홀수",end="")

num=int(input())
yak=[]
for i in range(1,num+1):
  if(num%i==0):
    yak.append(i)
length=len(yak)
for i in range(length):
  print(yak[i],end=" ")

num=int(input())
yak=[]
for i in range(1,num+1):
  if num%i==0:
    yak.append(i)
length=len(yak)
if length==2:
  print("prime")
else:
  print("not prime")

aph=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
enter=input()
length=len(enter)
for i in range(length):
  for j in range(25):
    if(input[i]==aph[j]):
      print(aph[j+3],sep="",end="")

aph=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
enter=input()
length=len(enter)
for i in range(length):
  if enter[i]==" ":
    print(" ",end="")
  for j in range(25):
    
    if (enter[i]==aph[j]):
      print(aph[j+3],sep="",end="")

small=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
big=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
enter=input()
length=len(enter)

for i in range(length):
  if enter[i]>='a' and enter[i]<='z':
    for j in range(25):
      if small[j]==enter[i]:
        print(big[j],end="")
  elif enter[i]>='A' and enter[i]<='Z':
    for j in range(25):
      if big[j]==enter[i]:
        print(small[j],end="")
  else:
    print(enter[i],end="")



num=int(input())
arr=[['a']*(num+2) for i in range(num+2)]
y=1
x=(num+2)//2
arr[y][x]=1
k=2

while(k<=num*num):
  if(arr[y-1][x+1]=='a' and y-1>=1 and x+1<=num): ##정상적인 경우 
    y=y-1
    x=x+1
    arr[y][x]=k
    k+=1
  elif(arr[y-1][x+1]=='a' and y-1<1 and x+1<=num): ##y가 이상한경우
    y=num
    x=x+1
    arr[y][x]=k
    k+=1
  elif(arr[y-1][x+1]=='a' and x+1>num and y-1>=1): ##x가 이상한경우
    y=y-1
    x=1
    arr[y][x]=k
    k+=1
  elif(arr[y-1][x+1]=='a' and x+1>num and y-1<1): ##x,y 둘다 이상한경우
    y=y+1
    x=x
    arr[y][x]=k
    k+=1
  elif(arr[y-1][x+1]!='a'):
    y=y+1
    x=x
    arr[y][x]=k
    k+=1


for y in range(1,num+1):
  for x in range(1,num+1):
    print(arr[y][x],end="")
  print()





